language: scala

scala:
   - 2.13.1
   - 2.12.10

jdk:
   - openjdk11

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
   - bash <(curl -Ls https://coverage.codacy.com/get.sh)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/15b5367e5ba965a65a9a
    on_success: change
    on_failure: always
    on_start: never

deploy:
  provider: script
  script: bash publish.sh
  on:
    tags: true

