language: scala
scala:
   - 2.12.6
jdk:
   - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport codacyCoverage
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/15b5367e5ba965a65a9a
    on_success: change
    on_failure: always
    on_start: never
